[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "档案"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "PPT"
  url = "presentation"
  weight = 3

    
[[main]]
  identifier = "blog"
  name = "文字"
  url = "blog"
  weight = 4

[[main]]
  identifier = "coder"
  name = "代码"
  url = "coder"
  weight = 5

[[main]]
  identifier = "gz"
  name = "规则"
  url = "gz"
  weight = 6

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 7

[[main]]
  parent = "gallery"
  name = "漫画"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "照片"
  url = "gallery/photo"

[[main]]
  identifier = "contact"
  name = "联系"
  url = "contact"
  weight = 8


[[main]]
  identifier = "showcase"
  name = "链接"
  url = "showcase"
  weight = 9