[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "档案"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "PPT"
  url = "presentation"
  weight = 3

    
[[main]]
  identifier = "data"
  name = "日记本"
  url = "data"
  weight = 4

[[main]]
  identifier = "coder"
  name = "码人生"
  url = "coder"
  weight = 5

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 6

[[main]]
  parent = "gallery"
  name = "漫画"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "照片"
  url = "gallery/photo"