[[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 1

    
[[main]]
  identifier = "data"
  name = "日记本"
  url = "data"
  weight = 2

[[main]]
  identifier = "coder"
  name = "码人生"
  url = "coder"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery"
  weight = 4

[[main]]
  parent = "gallery"
  name = "画"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "照片"
  url = "gallery/photo"