# Override these settings with your own
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
baseURL = "https://www.liqiangxo.one/"

copyright = "©{year}, All Rights Reserved" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true

# The value "hugo-theme-codex" is only to get the exampleSite
# to work in this repo. Change to whatever name you gave the theme
# when you added it. If you followed the README, you should have 
# added the theme using the name "codex".
theme = "zzo" 

title = "LQ" # Title of your site

enableGitInfo = false # When true, the modified date will appear on a summary and single page. Since GitHub info needs to be fetched, this feature will slow down to build depending on a page number you have

# REMOVE THIS!
# This is only to get the exampleSite to work in this repo.
# themesDir = "./" 

# Add your Disqus shortname here.
[params.valine]
    enable = true
    appId = '1fVnzL30puihhMql5HS0pwm4-gzGzoHsz'
    appKey = 'kYMC0bQQ0EXTJUJuFMDh2jF7'
    notify = false 
    verify = false 
    avatar = 'mm'
    placeholder = '说点什么吧...'
    visitor = true
paginate = 10
# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "456" 

canonifyurls = true
publishDir = "./liqiangxo"

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/liqiangxo"
  github = "https://github.com/liqiangxo"
  email = "mailto:liqiangxo@sina.cn"
  # facebook = "https://facebook.com/<your handle>"
  gitlab = "https://gitlab.com/liqiangxo"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconTitles = ["Twitter", "GitHub", "Email", "GitLab"]

googleAnalytics = ""
# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
# [markup]
#   [markup.highlight]
#     codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
#   [markup.goldmark.renderer]
#       unsafe = true

# Controls the navigation
# [[menu.main]]
#   identifier = "liqiangxo"
#   name = "Hallo world!"
#   title = "liqiangxo"
#   url = "/"
# [[menu.main]]
#   identifier = "data"
#   name = "日记本"
#   title = "data"
#   url = "/data"

# [[menu.main]]
#   identifier = "coder"
#   name = "码人生"
#   title = "coder"
#   url = "/coder"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"